name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    steps:
      - uses: actions/checkout@v4

      - name: Run build script
        run: bash ./build-static.sh ${{ github.ref_name }}

      - name: Package
        env:
          ZSTD_CLEVEL: 19
          ZSTD_NBTHREADS: 2
        run: |
          cd installed-static
          tar -acf ../qt-somewhere-static-${{ github.ref_name }}-archlinux-x86_64.tar.zst .

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: qt-somewhere-static-${{ github.ref_name }}-archlinux-x86_64.tar.zst
          tag: ${{ github.ref }}
          file_glob: false
          overwrite: true
          prerelease: false
